import Foundation
import SwiftUI
import simd

/// Reader/writer for MetaImage single-file volumes (`.mha`).
///
/// The AutoPET V Grand Challenge interface uses MHA for CT, PET, and output
/// lesion masks. This implementation supports the common uncompressed
/// `ElementDataFile = LOCAL` form written by SimpleITK, plus single external
/// raw data files referenced from an `.mhd` header.
public enum MetaImageIO {
    public enum Error: Swift.Error, LocalizedError {
        case fileNotFound(String)
        case invalidHeader(String)
        case unsupported(String)
        case payloadTooShort(expected: Int, actual: Int)

        public var errorDescription: String? {
            switch self {
            case .fileNotFound(let path):
                return "MetaImage file not found: \(path)"
            case .invalidHeader(let message):
                return "Invalid MetaImage header: \(message)"
            case .unsupported(let message):
                return "Unsupported MetaImage file: \(message)"
            case .payloadTooShort(let expected, let actual):
                return "MetaImage payload too short: expected \(expected) bytes, got \(actual)."
            }
        }
    }

    public struct HeaderSummary: Equatable, Sendable {
        public let width: Int
        public let height: Int
        public let depth: Int

        public var imageCount: Int { max(1, depth) }
    }

    private struct Header {
        let fields: [String: String]
        let dataFile: String
        let payloadOffset: Int
    }

    public static let extensions = ["mha", "mhd"]

    public static func isVolumeFile(_ url: URL) -> Bool {
        let name = url.lastPathComponent.lowercased()
        return extensions.contains { name.hasSuffix(".\($0)") }
    }

    public static func canonicalSourcePath(for url: URL) -> String {
        ImageVolume.canonicalPath(url.path)
    }

    public static func seriesUID(for url: URL) -> String {
        "mha:\(canonicalSourcePath(for: url))"
    }

    public static func headerSummary(_ url: URL) throws -> HeaderSummary {
        let data = try readFile(url)
        let header = try parseHeader(data)
        let dims = try dimensions(from: header.fields)
        return HeaderSummary(width: dims.width, height: dims.height, depth: dims.depth)
    }

    public static func load(_ url: URL,
                            modalityHint: String = "",
                            metadata: NIfTILoadMetadata = NIfTILoadMetadata()) throws -> ImageVolume {
        let data = try readFile(url)
        let header = try parseHeader(data)
        return try parseVolume(data: data,
                               header: header,
                               url: url,
                               modalityHint: modalityHint,
                               metadata: metadata)
    }

    public static func loadLabelMap(from url: URL,
                                    parentVolume: ImageVolume? = nil) throws -> LabelMap {
        let volume = try load(url, modalityHint: "SEG")
        var voxels = [UInt16](repeating: 0, count: volume.pixels.count)
        for i in volume.pixels.indices {
            let value = volume.pixels[i]
            if value > 0, value < Float(UInt16.max) {
                voxels[i] = UInt16(value.rounded())
            }
        }

        if let parentVolume {
            guard parentVolume.width == volume.width,
                  parentVolume.height == volume.height,
                  parentVolume.depth == volume.depth else {
                throw LabelIO.LabelIOError.geometryMismatch(
                    "labelmap \(volume.width)x\(volume.height)x\(volume.depth), current volume \(parentVolume.width)x\(parentVolume.height)x\(parentVolume.depth)"
                )
            }
        }

        let label = LabelMap(
            parentSeriesUID: parentVolume?.seriesUID ?? "",
            depth: volume.depth,
            height: volume.height,
            width: volume.width,
            name: url.deletingPathExtension().lastPathComponent
        )
        label.voxels = voxels
        label.classes = autogeneratedClasses(from: voxels)
        return label
    }

    public static func write(_ volume: ImageVolume, to url: URL) throws {
        var data = metaImageHeader(
            width: volume.width,
            height: volume.height,
            depth: volume.depth,
            spacing: volume.spacing,
            origin: volume.origin,
            direction: volume.direction,
            elementType: "MET_FLOAT"
        )
        for value in volume.pixels {
            var bits = value.bitPattern.littleEndian
            withUnsafeBytes(of: &bits) { data.append(contentsOf: $0) }
        }
        try data.write(to: url, options: [.atomic])
    }

    public static func writeLabelMap(_ label: LabelMap,
                                     to url: URL,
                                     parentVolume: ImageVolume,
                                     binary: Bool = false) throws {
        var data = metaImageHeader(
            width: label.width,
            height: label.height,
            depth: label.depth,
            spacing: parentVolume.spacing,
            origin: parentVolume.origin,
            direction: parentVolume.direction,
            elementType: binary ? "MET_UCHAR" : "MET_USHORT"
        )
        if binary {
            for voxel in label.voxels {
                data.append(voxel == 0 ? 0 : 1)
            }
        } else {
            for voxel in label.voxels {
                var value = voxel.littleEndian
                withUnsafeBytes(of: &value) { data.append(contentsOf: $0) }
            }
        }
        try data.write(to: url, options: [.atomic])
    }

    // MARK: - Parsing

    private static func readFile(_ url: URL) throws -> Data {
        guard FileManager.default.fileExists(atPath: url.path) else {
            throw Error.fileNotFound(url.path)
        }
        return try Data(contentsOf: url)
    }

    private static func parseHeader(_ data: Data) throws -> Header {
        var fields: [String: String] = [:]
        var offset = 0

        while offset < data.count {
            guard let lineEnd = data[offset...].firstIndex(of: 0x0A) else {
                throw Error.invalidHeader("missing ElementDataFile line")
            }
            let lineData = data[offset..<lineEnd]
            offset = lineEnd + 1

            guard let rawLine = String(data: lineData, encoding: .ascii) else {
                throw Error.invalidHeader("header is not ASCII")
            }
            let line = rawLine
                .trimmingCharacters(in: CharacterSet(charactersIn: "\r"))
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !line.isEmpty, !line.hasPrefix("#") else { continue }

            let parts = line.split(separator: "=", maxSplits: 1, omittingEmptySubsequences: false)
            guard parts.count == 2 else { continue }
            let key = parts[0].trimmingCharacters(in: .whitespaces)
            let value = parts[1].trimmingCharacters(in: .whitespaces)
            fields[key.lowercased()] = value
            if key.caseInsensitiveCompare("ElementDataFile") == .orderedSame {
                return Header(fields: fields, dataFile: value, payloadOffset: offset)
            }
        }

        throw Error.invalidHeader("missing ElementDataFile")
    }

    private static func parseVolume(data: Data,
                                    header: Header,
                                    url: URL,
                                    modalityHint: String,
                                    metadata: NIfTILoadMetadata) throws -> ImageVolume {
        let fields = header.fields
        let ndims = Int(fields["ndims"] ?? "3") ?? 3
        guard ndims == 3 else {
            throw Error.unsupported("only 3D volumes are supported; got NDims=\(ndims)")
        }
        guard (fields["binarydata"] ?? "True").caseInsensitiveCompare("True") == .orderedSame else {
            throw Error.unsupported("ASCII ElementDataFile payloads are not supported")
        }
        if (fields["compresseddata"] ?? "False").caseInsensitiveCompare("True") == .orderedSame {
            throw Error.unsupported("compressed MetaImage payloads are not supported")
        }
        if Int(fields["elementnumberofchannels"] ?? "1") ?? 1 != 1 {
            throw Error.unsupported("multi-channel MetaImage payloads are not supported")
        }

        let dims = try dimensions(from: fields)
        let spacing = vector3(fields["elementspacing"] ?? fields["elementsize"], defaultValue: [1, 1, 1])
        let origin = vector3(fields["offset"] ?? fields["position"], defaultValue: [0, 0, 0])
        let direction = directionMatrix(fields["transformmatrix"])
        let elementType = (fields["elementtype"] ?? "").uppercased()
        guard !elementType.isEmpty else {
            throw Error.invalidHeader("missing ElementType")
        }

        let payload: Data
        if header.dataFile.caseInsensitiveCompare("LOCAL") == .orderedSame {
            payload = data.subdata(in: header.payloadOffset..<data.count)
        } else {
            let rawURL = url.deletingLastPathComponent().appendingPathComponent(header.dataFile)
            payload = try readFile(rawURL)
        }

        let count = dims.width * dims.height * dims.depth
        let pixels = try decodePixels(payload: payload,
                                      elementType: elementType,
                                      count: count,
                                      bigEndian: byteOrderIsBigEndian(fields))
        let modality = inferModality(filename: url.lastPathComponent, hint: modalityHint)
        let description = metadata.seriesDescription.isEmpty
            ? url.deletingPathExtension().lastPathComponent
            : metadata.seriesDescription
        return ImageVolume(
            pixels: pixels,
            depth: dims.depth,
            height: dims.height,
            width: dims.width,
            spacing: (spacing[0], spacing[1], spacing[2]),
            origin: (origin[0], origin[1], origin[2]),
            direction: direction,
            modality: modality,
            seriesUID: seriesUID(for: url),
            studyUID: metadata.studyUID.isEmpty ? "mha-study:\(url.deletingLastPathComponent().path)" : metadata.studyUID,
            patientID: metadata.patientID,
            patientName: metadata.patientName,
            accessionNumber: metadata.accessionNumber,
            studyDate: metadata.studyDate,
            studyTime: metadata.studyTime,
            bodyPartExamined: metadata.bodyPartExamined,
            seriesDescription: description,
            studyDescription: metadata.studyDescription,
            sourceFiles: [url.path]
        )
    }

    private static func dimensions(from fields: [String: String]) throws -> (width: Int, height: Int, depth: Int) {
        guard let dimText = fields["dimsize"] else {
            throw Error.invalidHeader("missing DimSize")
        }
        let dims = dimText.split(separator: " ").compactMap { Int($0) }
        guard dims.count >= 3, dims[0] > 0, dims[1] > 0, dims[2] > 0 else {
            throw Error.invalidHeader("DimSize must contain three positive integers")
        }
        return (dims[0], dims[1], dims[2])
    }

    private static func decodePixels(payload: Data,
                                     elementType: String,
                                     count: Int,
                                     bigEndian: Bool) throws -> [Float] {
        let bytesPerVoxel: Int
        switch elementType {
        case "MET_CHAR", "MET_UCHAR":
            bytesPerVoxel = 1
        case "MET_SHORT", "MET_USHORT":
            bytesPerVoxel = 2
        case "MET_INT", "MET_UINT", "MET_FLOAT":
            bytesPerVoxel = 4
        case "MET_DOUBLE":
            bytesPerVoxel = 8
        default:
            throw Error.unsupported("ElementType \(elementType)")
        }
        let expected = count * bytesPerVoxel
        guard payload.count >= expected else {
            throw Error.payloadTooShort(expected: expected, actual: payload.count)
        }

        var pixels = [Float](repeating: 0, count: count)
        for i in 0..<count {
            let offset = i * bytesPerVoxel
            switch elementType {
            case "MET_CHAR":
                pixels[i] = Float(Int8(bitPattern: payload[offset]))
            case "MET_UCHAR":
                pixels[i] = Float(payload[offset])
            case "MET_SHORT":
                let value = Int16(bitPattern: payload.readUInt16(at: offset, bigEndian: bigEndian))
                pixels[i] = Float(value)
            case "MET_USHORT":
                pixels[i] = Float(payload.readUInt16(at: offset, bigEndian: bigEndian))
            case "MET_INT":
                let value = Int32(bitPattern: payload.readUInt32(at: offset, bigEndian: bigEndian))
                pixels[i] = Float(value)
            case "MET_UINT":
                pixels[i] = Float(payload.readUInt32(at: offset, bigEndian: bigEndian))
            case "MET_FLOAT":
                pixels[i] = Float(bitPattern: payload.readUInt32(at: offset, bigEndian: bigEndian))
            case "MET_DOUBLE":
                pixels[i] = Float(Double(bitPattern: payload.readUInt64(at: offset, bigEndian: bigEndian)))
            default:
                break
            }
        }
        return pixels
    }

    private static func byteOrderIsBigEndian(_ fields: [String: String]) -> Bool {
        let value = fields["binarydatabyteordermsb"] ?? fields["elementbyteordermsb"] ?? "False"
        return value.caseInsensitiveCompare("True") == .orderedSame
    }

    private static func vector3(_ text: String?, defaultValue: [Double]) -> [Double] {
        guard let text else { return defaultValue }
        let values = text.split(separator: " ").compactMap { Double($0) }
        guard values.count >= 3 else { return defaultValue }
        return Array(values.prefix(3))
    }

    private static func directionMatrix(_ text: String?) -> simd_double3x3 {
        guard let text else { return matrix_identity_double3x3 }
        let m = text.split(separator: " ").compactMap { Double($0) }
        guard m.count >= 9 else { return matrix_identity_double3x3 }
        return simd_double3x3(
            SIMD3<Double>(m[0], m[3], m[6]),
            SIMD3<Double>(m[1], m[4], m[7]),
            SIMD3<Double>(m[2], m[5], m[8])
        )
    }

    private static func metaImageHeader(width: Int,
                                        height: Int,
                                        depth: Int,
                                        spacing: (x: Double, y: Double, z: Double),
                                        origin: (x: Double, y: Double, z: Double),
                                        direction: simd_double3x3,
                                        elementType: String) -> Data {
        let rowMajorDirection = [
            direction[0].x, direction[1].x, direction[2].x,
            direction[0].y, direction[1].y, direction[2].y,
            direction[0].z, direction[1].z, direction[2].z
        ].map(formatNumber).joined(separator: " ")
        let lines = [
            "ObjectType = Image",
            "NDims = 3",
            "BinaryData = True",
            "BinaryDataByteOrderMSB = False",
            "CompressedData = False",
            "TransformMatrix = \(rowMajorDirection)",
            "Offset = \(formatNumber(origin.x)) \(formatNumber(origin.y)) \(formatNumber(origin.z))",
            "ElementSpacing = \(formatNumber(spacing.x)) \(formatNumber(spacing.y)) \(formatNumber(spacing.z))",
            "DimSize = \(width) \(height) \(depth)",
            "ElementType = \(elementType)",
            "ElementDataFile = LOCAL"
        ]
        return Data((lines.joined(separator: "\n") + "\n").utf8)
    }

    private static func formatNumber(_ value: Double) -> String {
        String(format: "%.12g", value)
    }

    private static func inferModality(filename: String, hint: String) -> String {
        let trimmed = hint.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty { return trimmed }
        let lower = filename.lowercased()
        if lower.contains("pet") || lower.contains("suv") || lower.contains("_0001") { return "PT" }
        if lower.contains("ct") || lower.contains("_0000") { return "CT" }
        if lower.contains("seg") || lower.contains("mask") || lower.contains("label") { return "SEG" }
        return "OT"
    }

    private static func autogeneratedClasses(from voxels: [UInt16]) -> [LabelClass] {
        let colors: [Color] = [.red, .green, .blue, .yellow, .orange, .purple, .pink,
                               .cyan, .mint, .indigo, .teal, .brown]
        return Set(voxels.filter { $0 != 0 }).sorted().enumerated().map { index, value in
            LabelClass(
                labelID: value,
                name: value == 1 ? "Lesion" : "Label \(value)",
                category: .lesion,
                color: colors[index % colors.count]
            )
        }
    }
}

public enum MedicalVolumeFileIO {
    public static func isVolumeFile(_ url: URL) -> Bool {
        NIfTILoader.isVolumeFile(url) || MetaImageIO.isVolumeFile(url)
    }

    public static func canonicalSourcePath(for url: URL) -> String {
        ImageVolume.canonicalPath(url.path)
    }

    public static func headerImageCount(_ url: URL) -> Int {
        if NIfTILoader.isVolumeFile(url) {
            return (try? NIfTILoader.headerSummary(url).imageCount) ?? 1
        }
        if MetaImageIO.isVolumeFile(url) {
            return (try? MetaImageIO.headerSummary(url).imageCount) ?? 1
        }
        return 1
    }

    public static func load(_ url: URL,
                            modalityHint: String = "",
                            metadata: NIfTILoadMetadata = NIfTILoadMetadata()) throws -> ImageVolume {
        if MetaImageIO.isVolumeFile(url) {
            return try MetaImageIO.load(url, modalityHint: modalityHint, metadata: metadata)
        }
        return try NIfTILoader.load(url, modalityHint: modalityHint, metadata: metadata)
    }
}

private extension Data {
    func readUInt16(at offset: Int, bigEndian: Bool) -> UInt16 {
        let value = UInt16(self[offset]) | (UInt16(self[offset + 1]) << 8)
        return bigEndian ? value.byteSwapped : value
    }

    func readUInt32(at offset: Int, bigEndian: Bool) -> UInt32 {
        let value = UInt32(self[offset])
            | (UInt32(self[offset + 1]) << 8)
            | (UInt32(self[offset + 2]) << 16)
            | (UInt32(self[offset + 3]) << 24)
        return bigEndian ? value.byteSwapped : value
    }

    func readUInt64(at offset: Int, bigEndian: Bool) -> UInt64 {
        var value: UInt64 = 0
        for i in 0..<8 {
            value |= UInt64(self[offset + i]) << UInt64(i * 8)
        }
        return bigEndian ? value.byteSwapped : value
    }
}
